# Generated by Django 4.1.5 on 2023-04-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_categorygallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryGallery',
        ),
    ]
